#!/bin/sh

xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.
for display in $(xrandr -q | grep -v 'eDP' | grep "connected" | awk '{print $1}'); do
    case "$display" in
        HDMI*|DP*) xrandr --output eDP1 --off --output "$display" --auto --primary; break ;;
    esac
done
setbg &         # set the background with the `setbg` script

xrdb ${XDG_CONFIG_HOME:-${HOME}/.config}/x11/xresources &
xrdbpid=$! # Uncomment to use Xresources colors/settings on startup

autostart="mpd xcompmgr dunst unclutter pipewire remapd"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
