#!/bin/sh

xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.
xrandr --output eDP-1 --mode 1920x1080 --rate 59

setbg &         # set the background with the `setbg` script

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
xrdbpid=$! # Uncomment to use Xresources colors/settings on startup

# if xinput list | grep -q "TPPS/2 IBM TrackPoint"; then
#     xinput set-prop "TPPS/2 IBM TrackPoint" "Coordinate Transformation Matrix" 2, 0, 0, 0, 5, 0, 0, 0, 1
# fi

autostart="mpd xcompmgr dunst unclutter pipewire remapd"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
